# FMT-350: vilka MARG-genretermer är mappade till MARC-enums - eller något annat i KBV?
https://kbse.atlassian.net/browse/FMT-350

In [42]:
import pandas
import requests

## Vad är MARC enums och enum types i KBV?

Enumvärden (enum values) är värden som ofta kan användas i flera kodlistor (enum types). Värdena består av ett namn i klartext (enum value), en kod bestående av en bokstav eller siffra (code) som är det man anger i MARC:s fasta fält, och en svensk samt en engelsk etikett (label). Kodlistorna motsvarar olika positioner i MARC. Bokstavskoderna är inte unika, utan kan betyda olika saker i olika termlistor.

Av de 764 unika enum-värdena är 113 mappade, via exactMatch, till en marcgt-kod.

Läs mer om termerna här: https://id.loc.gov/vocabulary/marcgt.html
Läs mer om hur termerna/koderna används här: https://www.loc.gov/standards/sourcelist/genre-form.html

### Exempel

Värdet marc:LegalArticle, alltså koden "g", kan ingå i föjande kodlistor:
- marc:SerialsNatureType
- marc:BooksContentsType	
- marc:SerialsContentsType

In [18]:
df = pandas.read_csv('../../marc_enums.tsv', sep='\t')
df = df.dropna(axis=1, how='all')
df.info()
df.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 996 entries, 0 to 995
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   enumtype    996 non-null    object
 1   enumvalue   996 non-null    object
 2   alias       996 non-null    object
 3   code        764 non-null    object
 4   broader     764 non-null    object
 5   deprecated  764 non-null    object
 6   labe_sv     764 non-null    object
 7   label_en    708 non-null    object
 8   exactMatch  113 non-null    object
dtypes: object(9)
memory usage: 70.2+ KB

,enumtype,enumvalue,alias,code,broader,deprecated,labe_sv,label_en,exactMatch
0,marc:SerialsNatureType,marc:LegalArticle,marc:SerialsNatureType-g,g,UNDEF,UNDEF,Juridiska artiklar@sv,Legal articles@en,marcgt:lea
1,marc:BooksContentsType,marc:LegalArticle,marc:BooksContentsType-g,NaN,NaN,NaN,NaN,NaN,NaN
2,marc:SerialsContentsType,marc:LegalArticle,marc:SerialsContentsType-g,NaN,NaN,NaN,NaN,NaN,NaN
3,marc:BooksContentsType,marc:Legislation,marc:BooksContentsType-l,l,UNDEF,UNDEF,Lagar och författningar@sv,Legislation@en,marcgt:leg
4,marc:SerialsNatureType,marc:Legislation,marc:SerialsNatureType-l,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
df[["enumvalue"]].value_counts().head(5)

enumvalue
marc:Other           65
marc:Mixed            7
marc:Multicolored     7
marc:Synthetic        6
marc:OneColor         5
Name: count, dtype: int64

### Unika MARC-enums

In [19]:
# Unika värden
unique_values = df.dropna(subset=["code"])
unique_values.info()
unique_values.head(5)

<class 'pandas.core.frame.DataFrame'>
Index: 764 entries, 0 to 995
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   enumtype    764 non-null    object
 1   enumvalue   764 non-null    object
 2   alias       764 non-null    object
 3   code        764 non-null    object
 4   broader     764 non-null    object
 5   deprecated  764 non-null    object
 6   labe_sv     764 non-null    object
 7   label_en    708 non-null    object
 8   exactMatch  113 non-null    object
dtypes: object(9)
memory usage: 59.7+ KB

,enumtype,enumvalue,alias,code,broader,deprecated,labe_sv,label_en,exactMatch
0,marc:SerialsNatureType,marc:LegalArticle,marc:SerialsNatureType-g,g,UNDEF,UNDEF,Juridiska artiklar@sv,Legal articles@en,marcgt:lea
3,marc:BooksContentsType,marc:Legislation,marc:BooksContentsType-l,l,UNDEF,UNDEF,Lagar och författningar@sv,Legislation@en,marcgt:leg
6,marc:SerialsNatureType,marc:SerialsNatureType-h,UNDEF,h,marc:Biography,UNDEF,Biografi@sv,Biography@en,marcgt:bio
7,marc:BooksContentsType,marc:LawReportOrDigest,marc:BooksContentsType-w,w,UNDEF,UNDEF,Domstolsutslag@sv,Law reports and digests@en,marcgt:law
10,marc:SerialsNatureType,marc:Yearbook,marc:SerialsNatureType-y,y,UNDEF,UNDEF,Årsbok@sv,UNDEF,marcgt:yea

In [30]:
# Finns det några enums som är deprecated?
unique_values["deprecated"].value_counts()

deprecated
UNDEF    764
Name: count, dtype: int64

In [31]:
# Vilka koder används i flest termlistor ?
unique_values["code"].value_counts().head(5)

code
a    59
c    52
d    49
b    49
e    35
Name: count, dtype: int64

### MARC-enums som har en MARC Genre Term som exactMatch

In [15]:
# Mapped values
mapped = unique_values.loc[unique_values["exactMatch"].notna()]
mapped.info()
mapped.head(5)

<class 'pandas.core.frame.DataFrame'>
Index: 113 entries, 0 to 518
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   enumtype    113 non-null    object
 1   enumvalue   113 non-null    object
 2   alias       113 non-null    object
 3   code        113 non-null    object
 4   broader     113 non-null    object
 5   deprecated  113 non-null    object
 6   labe_sv     113 non-null    object
 7   label_en    113 non-null    object
 8   exactMatch  113 non-null    object
dtypes: object(9)
memory usage: 8.8+ KB

,enumtype,enumvalue,alias,code,broader,deprecated,labe_sv,label_en,exactMatch
0,marc:SerialsNatureType,marc:LegalArticle,marc:SerialsNatureType-g,g,UNDEF,UNDEF,Juridiska artiklar@sv,Legal articles@en,marcgt:lea
3,marc:BooksContentsType,marc:Legislation,marc:BooksContentsType-l,l,UNDEF,UNDEF,Lagar och författningar@sv,Legislation@en,marcgt:leg
6,marc:SerialsNatureType,marc:SerialsNatureType-h,UNDEF,h,marc:Biography,UNDEF,Biografi@sv,Biography@en,marcgt:bio
7,marc:BooksContentsType,marc:LawReportOrDigest,marc:BooksContentsType-w,w,UNDEF,UNDEF,Domstolsutslag@sv,Law reports and digests@en,marcgt:law
10,marc:SerialsNatureType,marc:Yearbook,marc:SerialsNatureType-y,y,UNDEF,UNDEF,Årsbok@sv,UNDEF,marcgt:yea

### MARC-enums som inte har en MARC Genre Term som exactMatch

In [16]:
# Unmapped values
unmapped = unique_values.loc[unique_values["exactMatch"].isna()]
unmapped.info()
unmapped.head(5)

<class 'pandas.core.frame.DataFrame'>
Index: 651 entries, 76 to 995
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   enumtype    651 non-null    object
 1   enumvalue   651 non-null    object
 2   alias       651 non-null    object
 3   code        651 non-null    object
 4   broader     651 non-null    object
 5   deprecated  651 non-null    object
 6   labe_sv     651 non-null    object
 7   label_en    595 non-null    object
 8   exactMatch  0 non-null      object
dtypes: object(9)
memory usage: 50.9+ KB

,enumtype,enumvalue,alias,code,broader,deprecated,labe_sv,label_en,exactMatch
76,marc:BooksLiteraryFormType,marc:ComicStrip,marc:BooksLiteraryFormType-c,c,UNDEF,UNDEF,Tecknad serie (OBSOLET)@sv,Comic strips@en,NaN
84,marc:BooksLiteraryFormType,marc:NotFictionNotFurtherSpecified,marc:BooksLiteraryFormType-0,0,UNDEF,UNDEF,Ej skönlitteratur@sv,Not fiction@en,NaN
90,marc:GovtAgencyType,marc:Multistate,marc:GovtAgencyType-m,m,UNDEF,UNDEF,Grupp av provinser@sv,Multistate@en,NaN
92,marc:GovtAgencyType,marc:InternationalIntergovernmental,marc:GovtAgencyType-i,i,UNDEF,UNDEF,Övernationell (t.ex. EU)@sv,International intergovernmental@en,NaN
94,marc:GovtAgencyType,marc:Multilocal,marc:GovtAgencyType-c,c,UNDEF,UNDEF,Flera lokala@sv,Multilocal@en,NaN

In [51]:
marcgts = requests.get("https://id.loc.gov/vocabulary/marcgt", headers={"Accept": "application/json"}).json()

In [79]:
for i in marcgts:
    if "http://www.loc.gov/mads/rdf/v1#Authority" in i["@type"]:
        print(i["@id"][-3:], "\t", i.get("http://www.loc.gov/mads/rdf/v1#authoritativeLabel")[0].get("@value"))

rev 	 review
atl 	 atlas
lan 	 language instruction
mot 	 motion picture
dra 	 drama
com 	 computer program
ins 	 instruction
his 	 history
fon 	 font
sur 	 survey of literature
art 	 article
num 	 numeric data
lec 	 legal case and case notes
han 	 handook
map 	 map
sta 	 statistics
pro 	 programmed text
loo 	 loose-leaf
doc 	 document (computer)
reh 	 rehearsal
pos 	 postcard
fin 	 finding aid
mem 	 memoir
law 	 law report or digest
arr 	 art reproduction
rea 	 realia
ess 	 essay
aro 	 art original
lea 	 legal article
enc 	 encyclopedia
ser 	 series
stp 	 standard or specifications
hum 	 humor, satire
vid 	 videorecording
wal 	 wall map
sli 	 slide
mic 	 microscope slide
off 	 offprint
dir 	 directory
rem 	 remote sensing image
man 	 manuscript
kit 	 kit
boo 	 book
gov 	 government publication
poe 	 poetry
rep 	 representational
web 	 web site
tra 	 transparency
inm 	 interactive multimedia
dio 	 diorama
iss 	 issue
puz 	 puzzle
pat 	 patent
leg 	 legislation
per 	 periodical
ons 	 online system or service
nos 	 nonmusical sound
fla 	 flash card
cal 	 calendar
gra 	 graphic
scr 	 script
new 	 newspaper
rpt 	 reporting
glo 	 globe
sho 	 short story
fol 	 folktale
dic 	 dictionary
fes 	 festschrift
gam 	 game
ind 	 index
toy 	 toy
cpb 	 conference publication
jou 	 journal
spe 	 speech
bib 	 bibliography
the 	 thesis
ter 	 technical report
dis 	 discography
dtb 	 database
fil 	 filmography
int 	 interview
sou 	 sound
bio 	 biography
abs 	 abstract or summary
pic 	 picture
cha 	 chart
fls 	 filmstrip
mod 	 model
cat 	 catalog
cgn 	 comic or graphic novel
pla 	 playing cards
let 	 letter
cod 	 comedy
fic 	 fiction
bda 	 bibliographic data
aut 	 autobiography
nov 	 novel
tre 	 treaty

In [77]:
codes = [f'marcgt:{i["@id"][-3:]}' for i in marcgts if "http://www.loc.gov/mads/rdf/v1#Authority" in i["@type"]]
print(len(codes))
print(codes)

98
['marcgt:rev', 'marcgt:atl', 'marcgt:lan', 'marcgt:mot', 'marcgt:dra', 'marcgt:com', 'marcgt:ins', 'marcgt:his', 'marcgt:fon', 'marcgt:sur', 'marcgt:art', 'marcgt:num', 'marcgt:lec', 'marcgt:han', 'marcgt:map', 'marcgt:sta', 'marcgt:pro', 'marcgt:loo', 'marcgt:doc', 'marcgt:reh', 'marcgt:pos', 'marcgt:fin', 'marcgt:mem', 'marcgt:law', 'marcgt:arr', 'marcgt:rea', 'marcgt:ess', 'marcgt:aro', 'marcgt:lea', 'marcgt:enc', 'marcgt:ser', 'marcgt:stp', 'marcgt:hum', 'marcgt:vid', 'marcgt:wal', 'marcgt:sli', 'marcgt:mic', 'marcgt:off', 'marcgt:dir', 'marcgt:rem', 'marcgt:man', 'marcgt:kit', 'marcgt:boo', 'marcgt:gov', 'marcgt:poe', 'marcgt:rep', 'marcgt:web', 'marcgt:tra', 'marcgt:inm', 'marcgt:dio', 'marcgt:iss', 'marcgt:puz', 'marcgt:pat', 'marcgt:leg', 'marcgt:per', 'marcgt:ons', 'marcgt:nos', 'marcgt:fla', 'marcgt:cal', 'marcgt:gra', 'marcgt:scr', 'marcgt:new', 'marcgt:rpt', 'marcgt:glo', 'marcgt:sho', 'marcgt:fol', 'marcgt:dic', 'marcgt:fes', 'marcgt:gam', 'marcgt:ind', 'marcgt:toy', 'marcgt:cpb', 'marcgt:jou', 'marcgt:spe', 'marcgt:bib', 'marcgt:the', 'marcgt:ter', 'marcgt:dis', 'marcgt:dtb', 'marcgt:fil', 'marcgt:int', 'marcgt:sou', 'marcgt:bio', 'marcgt:abs', 'marcgt:pic', 'marcgt:cha', 'marcgt:fls', 'marcgt:mod', 'marcgt:cat', 'marcgt:cgn', 'marcgt:pla', 'marcgt:let', 'marcgt:cod', 'marcgt:fic', 'marcgt:bda', 'marcgt:aut', 'marcgt:nov', 'marcgt:tre']

In [78]:
mapped_codes = []
unmapped_codes = []
for c in codes:
    if c in unique_values["exactMatch"].values:
        mapped_codes.append(c)
    else:
        unmapped_codes.append(c)

print("Number of codes mapped in construct_enums:", len(mapped_codes))

print("Number of codes not mapped in construct_enums:", len(unmapped_codes))

print("\nUnmapped codes:", unmapped_codes)

Number of codes mapped in construct_enums: 88
Number of codes not mapped in construct_enums: 10

Unmapped codes: ['marcgt:art', 'marcgt:map', 'marcgt:fin', 'marcgt:rem', 'marcgt:boo', 'marcgt:iss', 'marcgt:nos', 'marcgt:scr', 'marcgt:jou', 'marcgt:mod']

**Finns i source/genreforms/genreforms.ttl (closeMatch)**
- marcgt:art
- marcgt:map
- marcgt:rem
- marcgt:boo
- marcgt:iss
- marcgt:scr
- marcgt:mod

**Finns i source/genreforms/rdacategories.ttl (closeMatch)**
- marcgt:nos

**Finns i source/genreforms/contentgenres.ttl (closeMatch)**
- marcgt:jou
- marcgt:fin